[package]
org = "praveesha"
name = "HopelyBackend"
version = "0.1.0"
distribution = "2201.12.3"

[build-options]
observabilityIncluded = true

[dependencies]
ballerina.http = "*"
ballerina.jwt = "*"
ballerina.crypto = "*"
ballerina.time = "*"
ballerina.uuid = "*"